name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Prepare Upload Artifact
        run: |
          mkdir artifacts
          cp target/release/tmux-cpu-rs artifacts/tmux-cpu-rs-x86_64-linux

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/tmux-cpu-rs-x86_64-linux
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
